### ISSUE TITLE
Comboboxes do not show touch effect

### ISSUE THREAD

**Issue by pablo-s** [allcount/allcountjs-ionic#1]
I just created a AllcountJS project based on Point of Sale demo and created the Android application using Ionic.

When editing those entities that have comboboxes (they are related to another entity), it is not possible to see the touch effect it that widget.

It is possible to pick one of the options, touch in "ok" and it works, but users cannot see they have pushed an option.

**Comment by paveltiunov** [comment]
Yep. There's API backward incompatible changes in ionic: new `ion-radio` tag.
