### ISSUE TITLE
Wrong left side menu format

### ISSUE THREAD

**Issue by pablo-s** [allcount/allcountjs-ionic#2]
I just created a new AllcountJS project and its Android application using Ionic.

After that I realized that the menu format is wrong. 

In the case of Point of Sale demo, it has Transactions, Items and Orders as menu entries.
The menu has the following format: 
- Transactions
- User
- Logout
- Items
- User
- Logout
- ... (same pattern for the rest of entries)

**Comment by paveltiunov** [comment]
@pablo-s Nice catch! Seems like an issue with hierarchy.
